# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release-type:
        descripton: 'Release Type (major | minor | patch)'
        required: true
        default: 'patch'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF: $GITHUB_SHA"
          echo "github.head_ref[PR Source] ${{ github.head_ref }}"
          echo "github.base_ref[PR Target] ${{ github.base_ref }}"
          echo "github.ref ${{ github.ref }}"
          echo "github.sha ${{ github.sha }}"
          echo "github.workflow ${{ github.workflow }}"

      # Bump version
      - name: Bump Version
        id: tag_version
        uses: zwaldowski/semver-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump: ${{ github.event.inputs.release-type }}
          dry_run: true

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}