name: Release
on:
  push:
    branches:
      - 'main'
      - '(releases?)?[0-9]+.[0-9]+.x'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    pull_request:
      types:
        - labeled

jobs:
  release:
    if: github.event.action != 'labeled'
    runs-on: ubunti-latest
    steps:
      - uses: actions/checkout@v2

      - id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1

      - run: echo "update version to $VERSION"
        if: "!steps.bumpr.outputs.skip"
        env:
          VERSION: ${{ steps.bumpr.outputs.next_version }}

  release-check:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post bumpr comment
        uses: haya14busa/action-bumpr@v1

